-- Lyra AI Agent — Strategy Registry, per-strategy trade log, and agent memory.
-- These tables power the autonomous strategy execution loop and self-improvement engine.

-- ─── lyra_strategies ──────────────────────────────────────────────────────────
-- Versioned strategy store. Each evolution of a strategy creates a new row
-- with parent_id pointing to the previous version.

create table if not exists public.lyra_strategies (
  id                uuid primary key default gen_random_uuid(),
  workspace_user_id uuid not null references public.workspace_users(id) on delete cascade,

  name              text not null,
  description       text,

  -- 'native'          — JSON condition tree (Lyra DSL)
  -- 'pine_script'     — TradingView Pine Script (stored in code->>'script')
  -- 'claude_generated' — generated by Claude, same shape as native
  type              text not null default 'native'
    check (type in ('native', 'pine_script', 'claude_generated')),

  -- Strategy logic. For native/claude_generated:
  --   { entry_conditions, exit_conditions, products, direction, max_leverage }
  -- For pine_script:
  --   { script: "<Pine Script text>" }
  code              jsonb not null default '{}'::jsonb,

  -- Tunable parameters (overlaid on code defaults at runtime)
  parameters        jsonb not null default '{}'::jsonb,

  version           integer not null default 1,

  -- Lineage — which version this evolved from
  parent_id         uuid references public.lyra_strategies(id) on delete set null,

  -- Lifecycle: draft → backtesting → paper → live → retired
  status            text not null default 'draft'
    check (status in ('draft', 'backtesting', 'paper', 'live', 'retired')),

  -- Running performance metrics (updated after each trade closes)
  performance       jsonb not null default jsonb_build_object(
    'total_trades',   0,
    'winning_trades', 0,
    'losing_trades',  0,
    'total_pnl_usd',  0,
    'win_rate',       null,
    'sharpe',         null,
    'max_drawdown',   null,
    'profit_factor',  null
  ),

  -- Webhook secret for TradingView alert routing
  webhook_secret    text not null default encode(gen_random_bytes(16), 'hex'),

  activated_at      timestamptz,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

create index if not exists lyra_strategies_workspace_user_id_idx
  on public.lyra_strategies (workspace_user_id, created_at desc);

create index if not exists lyra_strategies_status_idx
  on public.lyra_strategies (workspace_user_id, status);

create or replace trigger lyra_strategies_set_updated_at
before update on public.lyra_strategies
for each row execute function public.set_updated_at();

alter table public.lyra_strategies enable row level security;

-- ─── lyra_strategy_trades ─────────────────────────────────────────────────────
-- Per-strategy trade log. Used for performance tracking and self-improvement
-- (reflection loop reads the last N trades for a strategy).

create table if not exists public.lyra_strategy_trades (
  id                uuid primary key default gen_random_uuid(),
  strategy_id       uuid not null references public.lyra_strategies(id) on delete cascade,
  workspace_user_id uuid not null references public.workspace_users(id) on delete cascade,

  product_id        text not null,
  direction         text not null check (direction in ('long', 'short')),
  entry_price       numeric(24, 8) not null,
  exit_price        numeric(24, 8),
  notional_usd      numeric(24, 8) not null,
  leverage          integer not null default 1,

  pnl_usd           numeric(24, 8),
  outcome           text check (outcome in ('win', 'loss', 'breakeven')),

  -- Claude's post-trade analysis text (populated by the reflection loop)
  reflection        text,

  open_ts           timestamptz not null default now(),
  close_ts          timestamptz,
  created_at        timestamptz not null default now()
);

create index if not exists lyra_strategy_trades_strategy_id_idx
  on public.lyra_strategy_trades (strategy_id, created_at desc);

create index if not exists lyra_strategy_trades_workspace_user_id_idx
  on public.lyra_strategy_trades (workspace_user_id, created_at desc);

alter table public.lyra_strategy_trades enable row level security;

-- ─── lyra_agent_memory ────────────────────────────────────────────────────────
-- Lyra's persistent learning store. The self-improvement loop writes lessons
-- here; get_agent_memory MCP tool surfaces them to Claude.

create table if not exists public.lyra_agent_memory (
  id                uuid primary key default gen_random_uuid(),
  workspace_user_id uuid not null references public.workspace_users(id) on delete cascade,

  -- 'market_insight'  — observation about a specific market condition
  -- 'strategy_lesson' — what worked / didn't work for a strategy
  -- 'pattern'         — recurring setup or signal pattern
  -- 'risk_note'       — risk management observation
  memory_type       text not null
    check (memory_type in ('market_insight', 'strategy_lesson', 'pattern', 'risk_note')),

  content           text not null,

  -- 0.0 = speculative, 1.0 = high-confidence observed fact
  confidence        numeric(4, 3) not null default 0.5
    check (confidence >= 0 and confidence <= 1),

  -- Optionally linked to a specific strategy
  strategy_id       uuid references public.lyra_strategies(id) on delete set null,

  created_at        timestamptz not null default now()
);

create index if not exists lyra_agent_memory_workspace_user_id_idx
  on public.lyra_agent_memory (workspace_user_id, created_at desc);

alter table public.lyra_agent_memory enable row level security;

-- ─── update_strategy_performance() ───────────────────────────────────────────
-- Called after each strategy trade closes to keep the performance JSONB current.
-- Win rate, profit factor, and total PnL are derived from the trade log.

create or replace function public.lyra_update_strategy_performance(
  p_strategy_id uuid
)
returns void
language plpgsql
security definer
as $$
declare
  v_total      integer;
  v_wins       integer;
  v_losses     integer;
  v_total_pnl  numeric;
  v_win_rate   numeric;
  v_gross_win  numeric;
  v_gross_loss numeric;
  v_pf         numeric;
begin
  select
    count(*)                                             into v_total,
    count(*) filter (where outcome = 'win')              into v_wins,
    count(*) filter (where outcome = 'loss')             into v_losses,
    coalesce(sum(pnl_usd), 0)                            into v_total_pnl,
    coalesce(sum(pnl_usd) filter (where pnl_usd > 0), 0) into v_gross_win,
    coalesce(abs(sum(pnl_usd)) filter (where pnl_usd < 0), 0) into v_gross_loss
  from public.lyra_strategy_trades
  where strategy_id = p_strategy_id
    and outcome is not null;

  v_win_rate := case when v_total > 0 then round((v_wins::numeric / v_total) * 100, 1) else null end;
  v_pf       := case when v_gross_loss > 0 then round(v_gross_win / v_gross_loss, 2) else null end;

  update public.lyra_strategies
  set performance = jsonb_build_object(
    'total_trades',   v_total,
    'winning_trades', v_wins,
    'losing_trades',  v_losses,
    'total_pnl_usd',  v_total_pnl,
    'win_rate',       v_win_rate,
    'profit_factor',  v_pf,
    'sharpe',         null,
    'max_drawdown',   null
  )
  where id = p_strategy_id;
end;
$$;
